saltstack-formulas/aptly-formula

aptly/aptly_config.sls

Not sure what the difference is, but sometimes gpg complains about not having a
tty. Sometimes it works fine. Let's just go ahead and be on the safe side and
add --no-tty option to all gpg calls.

Add --no-tty option to gpg commands

---

aptly/aptly_config.sls
aptly/create_repos.sls
aptly/publish_repos.sls

2015.2 doesn't seem to pass the env correctly. This shouldn't impact anything
<2015.2 and fixes an issue in 2015.2.

Add HOME env variable to cmd.run's

---

aptly/create_repos.sls
aptly/publish_repos.sls

The -batch=true option tells aptly to pass -no-tty to gpg commands (amongst
other things). It's required to not have the underlying gpg calls complain.

Add -batch=true option to aptly commands

---

aptly/create_repos.sls

I was using a pre-release version before. It just ignored the -batch option for !publish commands. The release version dies :sadface:

-batch option is only for publish commands

---

aptly/nginx.sls

I don't use the formulas nginx support, so I never noticed this was broken.
fixes #14

Add template:jinja to nginx template

---

aptly/create_repos.sls

Before we just blindly added all the packages all the time, but that made it
look like things were constantly changing. Check the number of packages in the
repo against the number of packages in the pkgdir, if it matches, skip adding.

Make the formula stop reporting changes when all packages already added

---

aptly/files/.aptly.conf.jinja
pillar.example

This commit fixes an error, which I met:
`              stderr:
ERROR: unable to publish: unable to figure out list of architectures, please supply explicit list
`

added possibility specify archs explicitly

---

aptly/aptly_config.sls
aptly/create_repos.sls
aptly/files/.aptly.conf.jinja
aptly/init.sls
aptly/publish_repos.sls
pillar.example

just a little cleanup
- ```opts['pkgdir']``` fails if you dont specify it. in the case that I do no want to (our setup), this should be optional so switched to defaulting the value to ```false``` as to not fail the states
- instead of passing ```architectures``` as a string with stringed comma-delimited values (in the hope that it parses out correctly), just accept an array and pass it through salts json filter
- optional ```uid``` and ```gid```
- ```publish_repos``` now takes an optional ```prefix``` . 
- ```publish_repos``` also makes ```gpg-keyid``` and ```gpgpassphrase``` optional and only appends them if available

 cleaning up aptly state for flexibility

---

aptly/files/.aptly.conf.jinja

as per @iggy  comment here: https://github.com/saltstack-formulas/aptly-formula/pull/27#issuecomment-228245988
We could also do this in one line, but this looks a little cleaner. would be happy to move to one line if necessary

 adding backwards compatiblity for architectures field

---

aptly/create_mirrors.sls
pillar.example

Many repositories need more than one key in the gpg keyring to allow mirroring.
This PR fixes https://github.com/saltstack-formulas/aptly-formula/issues/30

Bf aptly formula issue 30

---

aptly/create_mirrors.sls

Fix for https://github.com/saltstack-formulas/aptly-formula/issues/35
In addition:
1) Support using the same keyring for different repos without failing.
2) Allow the formula to be a no op if no mirrors defined.
Signed-off-by: Owen Synge <owen.synge@jaysnest.de>

Only call keyring server when we need to.

---

aptly/publish_repos.sls

if we upload already existing version of package to upload dir, aptlu will fail without this flag.
If we will use this flag, aptly would overwrite file.

FIX version conflict behavior

---

aptly/aptly_config.sls
aptly/create_mirrors.sls
pillar.example

Hello,
This PR allows to use another *gnupg* command. It should help on *Debian Stretch+* systems which  use *gnupg 2.x* by default.
See https://www.aptly.info/doc/feature/pgp-providers/ for details.
It should not affect existing setups.
Thanks.

Allow to specify the gpg command to use

---

aptly/aptly_config.sls
aptly/create_mirrors.sls
aptly/create_repos.sls
aptly/publish_repos.sls

Hello,
The *runas* argument should be used with *cmd.run* instead of *user", which has been deprecated a long time ago. See https://github.com/saltstack/salt/issues/11179 for details.
Thanks.

Use runas argument for cmd.run instead of user

---

aptly/create_mirrors.sls
pillar.example

Hello,
The *aptly mirror* command supports *-filter* and *-filter-with-deps* arguments which allow to create mirrors on a per packages query basis.
See https://www.aptly.info/doc/feature/query/ for details.
Thanks.

Support filter and filter-with-deps arguments

---

aptly/create_repos.sls

aptly.create_repos is broken due to a missing import from map.jinja, causing a render error:
```
root@master:~# salt-call state.apply aptly.create_repos
[ERROR   ] Rendering exception occurred: Jinja variable 'aptly' is undefined
[CRITICAL] Rendering SLS 'base:aptly.create_repos' failed: Jinja variable 'aptly' is undefined
local:
Data failed to compile:
----------
Rendering SLS 'base:aptly.create_repos' failed: Jinja variable 'aptly' is undefined
```
The import fixes it.

Add import for aptly from Jinja template

---

aptly/files/.aptly.conf.jinja

Hello,
Some pillar keys can be overrided in *aptly:lookup* thanks to `map.jinja`.
This PR fix pillar usage in `.aptly.conf.jinja`.

Fix pillar usage

---

aptly/publish_repos.sls

This PR fixes the incomplete commands to grab pillar info, resulting in:
```
local:
Data failed to compile:
----------
Rendering SLS 'base:aptly.publish_repos' failed: Jinja syntax error: expected token 'end of statement block', got 'string'; line 3
---
{% from "aptly/map.jinja" import aptly with context %}
{% set architectures = pillar.get']('aptly:architectures', {}) %}    <======================
{% set gpgid = salt['pillar.get']('aptly:gpg_keypair_id', '') %}
{% set gpgpassphrase = salt['pillar.get']('aptly:gpg_passphrase', '') %}
{% set repos = pillar.get']('aptly:repos', {}) %}
include:
[...]
---
```

Fix publish_repos: Jinja syntax error

---

aptly/aptly_config.sls
aptly/create_mirrors.sls
aptly/create_repos.sls
aptly/init.sls
aptly/map.jinja
aptly/publish_repos.sls
pillar.example

The user is currently hardcoded to `aptly`. This is annoying, because changing this is practically impossible. 
I've tried to achieve this with a bunch of `extend:` entries but for instance in the `publish_repos` and `create_repos` which uses a loop. 
This PR adds the ability to change the user, it defaults to `aptly` in the pillar data and map so it should be perfectly backwards compatible with people who prefer to keep using the `aptly` user rather than a different one.

Made the user configurable

---

aptly/create_repos.sls

The `user` argument to `cmd.run` doesn't do anything anymore since it has been replaced with `runas` quite some time ago.
Note: This PR may conflict with #54

Fix create_repos: Use runas instead of user
